Repository Apollo-11/leda, pull requests merged in 2020-04, with the labels that each got.

#116 FileProp: new API
  demo/components/FileDrop/ControlledFileDrop.tsx
  leda/components/DropZone/helpers.tsx
  leda/components/DropZone/types.ts
  leda/components/FileDrop/FileDrop.tsx
  leda/components/FileDrop/ProgressLoader.tsx
  leda/components/FileDrop/SingleFileView.tsx
  leda/components/FileDrop/handlers.ts
  leda/components/FileDrop/helpers.tsx
  leda/components/FileDrop/hooks.ts
  leda/components/FileDrop/types.ts
  leda/components/FileUpload/helpers.ts
  leda/components/FileUpload/types.ts
  leda/constants.ts
  leda/form/helpers.ts
Labels: feature

#117 FileDrop: update error types
  demo/components/FileDrop/ControlledFileDrop.tsx
  leda/components/FileDrop/types.ts
Labels: feature

#118 RadioButton: fix wrapperRender ref types conflict
  demo/components/Radio.tsx
  leda/commonTypes/index.ts
  leda/components/Radio/RadioButton.tsx
  leda/components/Radio/RadioGroup.tsx
  leda/components/Radio/types.ts
  leda/utils/getWrapperRef.ts
  leda/utils/isLedaRefComponent.ts
Labels: bug, wip

#121 MultiSelect: add shouldKeepSuggestions, enable checkboxes
  demo/components/MultiSelect/CheckBoxes.tsx
  demo/components/MultiSelect/index.tsx
  leda/components/AutoComplete/types.ts
  leda/components/MultiSelect/helpers.ts
  leda/components/MultiSelect/index.tsx
  leda/components/MultiSelect/types.ts
  leda/src/SuggestionList/SuggestionItem.tsx
  leda/src/SuggestionList/helpers.ts
  leda/src/SuggestionList/types.ts
Labels: feature

#122 MultiSelect, DropDownSelect, AutoComplete: sort list feature
  demo/components/MultiSelect/CheckBoxes.tsx
  leda/components/AutoComplete/index.tsx
  leda/components/AutoComplete/types.ts
  leda/components/DropDownSelect/index.tsx
  leda/components/DropDownSelect/types.ts
  leda/components/MultiSelect/index.tsx
  leda/components/MultiSelect/types.ts
  leda/src/SuggestionList/SuggestionList.tsx
  leda/src/SuggestionList/helpers.ts
  leda/src/SuggestionList/types.ts
Labels: feature

#123 MultiSelect: add uniteTags prop
  demo/components/MultiSelect/CheckBoxes.tsx
  leda/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  leda/components/MultiSelect/handlers.ts
  leda/components/MultiSelect/helpers.ts
  leda/components/MultiSelect/index.tsx
  leda/components/MultiSelect/theme.ts
  leda/components/MultiSelect/types.ts
  leda/index.ts
  leda/utils/getWordEnding.ts
  leda/utils/index.ts
  styles/themes/light/components/MultiSelect/_multiselect.scss
Labels: feature

#124 MultiSelect: remove onEnterPress from types, it is not used
  leda/components/DropZone/types.ts
  leda/components/MultiSelect/types.ts
Labels: invalid

#126 Validation: fix shouldScrollToInvalidFields for missing forms
  demo/components/Validation/BasicUsage.tsx
  demo/components/Validation/index.tsx
  leda/components/Button/handlers.ts
  leda/components/Button/index.tsx
Labels: invalid

#127 Validation: export ValidationFailEvent
  leda/components/Button/types.ts
Labels: enhancement

#129 Div: add shouldRender prop
  leda/components/A/index.tsx
  leda/components/A/types.ts
  leda/components/Article/index.ts
  leda/components/Aside/index.ts
  leda/components/B/index.ts
  leda/components/Blockquote/index.ts
  leda/components/Button/index.tsx
  leda/components/Button/types.ts
  leda/components/Div/index.ts
  leda/components/Dl/types.ts
  leda/components/Figcaption/index.ts
  leda/components/Figure/index.ts
  leda/components/Footer/index.ts
  leda/components/Headers/types.ts
  leda/components/I/index.ts
  leda/components/Img/index.ts
  leda/components/Li/index.ts
  leda/components/Main/index.ts
  leda/components/Mark/index.ts
  leda/components/Nav/index.ts
  leda/components/Ol/index.ts
  leda/components/Paragraph/index.ts
  leda/components/Section/index.ts
  leda/components/Small/index.ts
  leda/components/Span/index.ts
  leda/components/Table/types.ts
  leda/components/Ul/index.ts
  leda/src/HTMLTagsFactory/index.tsx
Labels: help wanted, wip

#131 Button, Pagination: sort props
  leda/components/Button/types.ts
  leda/components/Pagination/types.ts
Labels: refactoring

#135 Required: add css-class "required" to all required fields
  leda/components/AutoComplete/__snapshots__/AutoComplete.test.tsx.snap
  leda/components/AutoComplete/index.tsx
  leda/components/AutoComplete/theme.ts
  leda/components/Button/__snapshots__/Buttons.test.tsx.snap
  leda/components/ButtonGroup/index.tsx
  leda/components/ButtonGroup/theme.ts
  leda/components/DateRange/__snapshots__/DateRange.test.tsx.snap
  leda/components/DropDownSelect/helpers.ts
  leda/components/DropDownSelect/index.tsx
  leda/components/DropDownSelect/theme.ts
  leda/components/DropDownSelect/types.ts
  leda/components/DropZone/DropZone.tsx
  leda/components/DropZone/__snapshots__/DropZone.test.tsx.snap
  leda/components/DropZone/theme.ts
  leda/components/FileDrop/FileDrop.tsx
  leda/components/FileDrop/theme.ts
  leda/components/Input/index.tsx
  leda/components/Input/theme.ts
  leda/components/LedaProvider/__snapshots__/LedaProvider.test.tsx.snap
  leda/components/MaskedInput/index.tsx
  leda/components/MaskedInput/theme.ts
  leda/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  leda/components/MultiSelect/index.tsx
  leda/components/MultiSelect/theme.ts
  leda/components/NumericTextBox/index.tsx
  leda/components/NumericTextBox/theme.ts
  leda/components/Password/index.tsx
  leda/components/Password/theme.ts
  leda/components/Textarea/index.tsx
  leda/components/Textarea/theme.ts
  leda/form/helpers.ts
  leda/src/DateTimeInput/helpers.ts
  leda/src/DateTimeInput/theme.ts
  leda/utils/getIsEmptyAndRequired.ts
  leda/utils/index.ts
Labels: feature

#132 Tabs: add tabContentRef prop
  demo/components/Tabs/Basic.tsx
  demo/components/Tabs/Customization.tsx
  demo/components/Tabs/TabsNode.tsx
  demo/components/Tabs/index.tsx
  leda/components/Tabs/ContentElement.tsx
  leda/components/Tabs/types.ts
  leda/index.ts
  leda/utils/index.ts
  leda/utils/useElementRef.ts
Labels: feature

#138 DateRange: add inputsRender prop
  demo/components/DateRange/Customization.tsx
  demo/components/DateRange/index.tsx
  leda/src/DateTimeInputRange/index.tsx
  leda/src/DateTimeInputRange/types.ts
Labels: feature

#139 DropDownSelect: add searchFields prop
  demo/components/DropDownSelect/SearchFields.tsx
  demo/components/DropDownSelect/index.tsx
  leda/components/DropDownSelect/helpers.ts
  leda/components/DropDownSelect/index.tsx
  leda/components/DropDownSelect/types.ts
Labels: feature

#141 MaskedInput: add new mask rules: x, w, z
  leda/components/MaskedInput/mask.md
  leda/src/MaskedInputBase/constants.ts
  leda/src/MaskedInputBase/types.ts
Labels: enhancement

#142 FileDrop: update naming
  demo/components/FileDrop/Customization.tsx
  leda/components/FileDrop/hooks.ts
  leda/components/FileDrop/types.ts
Labels: bug

#144 Validation: fix external validators
  demo/components/Validation/BasicUsage.tsx
  demo/components/Validation/Form.tsx
  demo/components/Validation/FormControlled.tsx
  demo/components/Validation/FormUncontrolled.tsx
  demo/components/Validation/InvalidMessage.tsx
  demo/components/Validation/IsValid.tsx
  demo/components/Validation/PredefinedValidator.tsx
  demo/components/Validation/Refactoring.tsx
  demo/components/Validation/Required.tsx
  demo/components/Validation/RequiredSubmit.tsx
  demo/components/Validation/Scroll.tsx
  demo/components/Validation/ShouldValidateUnmounted.tsx
  demo/components/Validation/Submit.tsx
  demo/components/Validation/TriggerValidation.tsx
  demo/components/Validation/ValidationMessageRender.tsx
  demo/components/Validation/Validator.tsx
  demo/components/Validation/index.tsx
  demo/types.ts
  leda/form/form.ts
  leda/form/helpers.ts
  leda/form/types.ts
Labels: bug

#145 Validation: add removal feature to the form helpers
  demo/components/Validation/ShouldValidateUnmounted.tsx
  leda/components/Validation/helpers.ts
  leda/components/Validation/types.ts
  leda/form/form.ts
  leda/form/types.ts
Labels: feature

#148 AutoComplete: better spaces handling when minSearchLength is set
  leda/components/AutoComplete/helpers.ts
  leda/components/AutoComplete/index.tsx
Labels: enhancement

#149 DropDownSelect: add null to value type
  leda/components/DropDownSelect/types.ts
Labels: bug

#146 fileDrop-disable: disable buttons on conditions
  demo/components/FileDrop/ControlledFileDrop.tsx
  leda/components/FileDrop/ErrorComponent.tsx
  leda/components/FileDrop/SingleFileView.tsx
  leda/components/FileDrop/SuccessComponent.tsx
  leda/components/FileDrop/types.ts
Labels: bug

#150 Validation: reset invalid state when isRequired changes
  demo/components/Validation/IsRequired.tsx
  demo/components/Validation/index.tsx
  leda/components/VStepper/helpers.tsx
  leda/components/VStepper/index.tsx
  leda/components/Validation/helpers.ts
Labels: enhancement

#151 Validation: add scrollDelay prop
  demo/components/Validation/Scroll.tsx
  leda/components/Button/handlers.ts
  leda/components/Button/index.tsx
  leda/components/Button/types.ts
Labels: feature

#147 NumericTextBox: add shouldTrimTrailingZeros prop
  demo/components/NumericTextBox/BasicUsage.tsx
  demo/components/NumericTextBox/TrailingZeros.tsx
  demo/components/NumericTextBox/index.tsx
  leda/components/NumericRange/handlers.ts
  leda/components/NumericRange/index.tsx
  leda/components/NumericRange/types.ts
  leda/components/NumericTextBox/handlers.ts
  leda/components/NumericTextBox/helpers.ts
  leda/components/NumericTextBox/hooks.tsx
  leda/components/NumericTextBox/index.tsx
  leda/components/NumericTextBox/types.ts
Labels: enhancement

#155 Styles: fix Font Awesome icons
  demo/Demo.tsx
  demo/components/Loader.tsx
  styles/themes/light/commonStyles/DropDownList/_dropdown-list.scss
  styles/themes/light/components/AutoComplete/_autocomplete.scss
  styles/themes/light/components/Button/_button.scss
  styles/themes/light/components/Calendar/_calendar.scss
  styles/themes/light/components/CheckBox/_checkbox.scss
  styles/themes/light/components/Collapse/_collapse.scss
  styles/themes/light/components/DateTimePicker/_datetimepicker.scss
  styles/themes/light/components/DropDownSelect/_dropdown-select.scss
  styles/themes/light/components/FileDrop/_file-drop.scss
  styles/themes/light/components/Input/_input.scss
  styles/themes/light/components/Modal/_modal.scss
  styles/themes/light/components/MultiSelect/_multiselect.scss
  styles/themes/light/components/NumericTextBox/_numeric.scss
  styles/themes/light/components/Pagination/_pagination.scss
  styles/themes/light/components/Password/_password.scss
  styles/themes/light/components/Rating/_rating.scss
  styles/themes/light/components/StatusBar/_statusbar.scss
  styles/themes/light/components/Tags/_tags.scss
  styles/themes/light/components/VStepper/_v-stepper.scss
Labels: invalid

#154 DropDownSelect: better searchFields handling
  demo/components/DropDownSelect/SearchFields.tsx
  leda/components/DropDownSelect/helpers.ts
Labels: enhancement

#153 DropDownSelect: fix arrow navigation when searchFields is set
  demo/components/DropDownSelect/SearchFields.tsx
  leda/components/DropDownSelect/handlers.ts
  leda/components/DropDownSelect/helpers.ts
  leda/components/DropDownSelect/hooks.ts
  leda/components/DropDownSelect/index.tsx
  leda/components/DropDownSelect/types.ts
Labels: bug

#152 Input, Textarea, Password: change maxLength UX, trim value, do not ignore
  leda/components/Input/Input.test.tsx
  leda/components/Input/handlers.ts
  leda/components/Password/handlers.ts
  leda/components/Textarea/Textarea.test.tsx
  leda/components/Textarea/handlers.ts
  leda/utils/helpers.ts
  leda/utils/index.ts
Labels: invalid

#156 Tabs: add scroll when there is too many tabs
  demo/components/Tabs/Scroll.tsx
  demo/components/Tabs/index.tsx
  leda/components/Tabs/ScrollArrows.tsx
  leda/components/Tabs/Tab.tsx
  leda/components/Tabs/Tabs.tsx
  leda/components/Tabs/__snapshots__/Tabs.test.tsx.snap
  leda/components/Tabs/hooks.ts
  leda/components/Tabs/theme.ts
  leda/components/Tabs/types.ts
  styles/themes/light/components/Tabs/_tabs.scss
Labels: enhancement

#159 Tour: new component
  demo/Demo.tsx
  demo/components/Tour.tsx
  demo/components/index.ts
  leda/components/Tour/Tour.tsx
  leda/components/Tour/helpers.ts
  leda/components/Tour/index.ts
  leda/components/Tour/types.ts
  leda/index.ts
  styles/themes/light/_styles.scss
  styles/themes/light/components/Tour/_tour.scss
Labels: feature

#160 Header: fix ref types
  leda/components/Headers/types.ts
Labels: bug

#162 FileDrop: fix file downloading
  demo/components/FileDrop/Basic.tsx
  demo/components/FileDrop/index.tsx
  leda/components/FileDrop/SingleFileView.tsx
  leda/components/FileDrop/handlers.ts
  leda/components/FileDrop/helpers.tsx
  leda/components/FileDrop/types.ts
Labels: bug

#163 Tour: fix scrolling to relative or fixed elements
  leda/components/Tour/Tour.tsx
Labels: bug

#165 FileDrop: fix fractional pixels
  leda/components/Tour/Tour.tsx
Labels: bug

#166 MultiSelect: add shouldHideInput prop
  demo/components/MultiSelect/NoInput.tsx
  demo/components/MultiSelect/index.tsx
  leda/components/MultiSelect/index.tsx
  leda/components/MultiSelect/types.ts
Labels: feature

#167 Tabs: fix scroll styles
  leda/components/Tabs/Tabs.tsx
  styles/themes/light/components/Tabs/_tabs.scss
Labels: bug
