Repository Apollo-11/leda, pull requests merged in 2020-03, with the labels that each got.

#44 Documentation: make sidebar panel static
  docs/system/helpers/index.ts
  docs/system/helpers/sidebarOpen.ts
  docs/system/layout/MainLayout.tsx
  docs/system/layout/SideNavigation.tsx
  styles/docs.scss
Labels: documentation

#17 FEND-956 Tooltip: fix style bug
  demo/components/Tooltip.tsx
  leda/components/Tooltip/Tooltip.test.tsx
  leda/components/Tooltip/TooltipBody.tsx
  leda/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
  leda/components/Tooltip/handlers.ts
  leda/components/Tooltip/helpers.ts
  leda/components/Tooltip/hooks.ts
  leda/components/Tooltip/index.tsx
  leda/components/Tooltip/types.ts
Labels: feature, jira

#41 add release workflow and update common configs
  .github/workflows/release.yml
  .npmignore
  .npmrc
  package-lock.json
  package.json
  webpack.analyze.js
  webpack.docs.js
Labels: feature, misc

#1 FEND-909 MultiSelect: create checkboxes
  demo/components/AutoComplete/CompareObjectsBy.tsx
  demo/components/MultiSelect/DataTypes.tsx
  demo/components/MultiSelect/GroupedData.tsx
  leda/commonTypes/index.ts
  leda/components/AutoComplete/handlers.ts
  leda/components/AutoComplete/helpers.ts
  leda/components/AutoComplete/index.tsx
  leda/components/AutoComplete/types.ts
  leda/components/DropDownSelect/index.tsx
  leda/components/LedaProvider/__snapshots__/LedaProvider.test.tsx.snap
  leda/components/MultiSelect/TagsContainer.tsx
  leda/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  leda/components/MultiSelect/handlers.ts
  leda/components/MultiSelect/helpers.ts
  leda/components/MultiSelect/index.tsx
  leda/components/MultiSelect/types.ts
  leda/index.ts
  leda/src/SuggestionList/GroupLabel.tsx
  leda/src/SuggestionList/SelectAll.tsx
  leda/src/SuggestionList/SuggestionItem.tsx
  leda/src/SuggestionList/SuggestionList.tsx
  leda/src/SuggestionList/handlers.ts
  leda/src/SuggestionList/helpers.ts
  leda/src/SuggestionList/theme.ts
  leda/src/SuggestionList/types.ts
  leda/utils/checkIsTheSameObject.ts
  leda/utils/helpers.ts
  leda/utils/index.ts
  package-lock.json
  styles/themes/leda/components/SuggestionList/_suggestion-list.scss
Labels: feature, jira

#49 StatusBar: fix typeField prop
  demo/components/StatusBar.tsx
  docs/Docs.tsx
  docs/constants.ts
  docs/index.tsx
  docs/lang/en.ts
  docs/lang/ru.ts
  docs/lang/types.ts
  docs/stories/Layout/StatusBar/API/En.tsx
  docs/stories/Layout/StatusBar/API/Ru.tsx
  docs/stories/Layout/StatusBar/API/StatusBarApi.tsx
  docs/stories/Layout/StatusBar/API/index.ts
  docs/stories/Layout/StatusBar/Props/En.tsx
  docs/stories/Layout/StatusBar/Props/Ru.tsx
  docs/stories/Layout/StatusBar/Props/StatusBarProps.tsx
  docs/stories/Layout/StatusBar/Props/StatusItemType.tsx
  docs/stories/Layout/StatusBar/Props/index.ts
  docs/stories/Layout/StatusBar/index.ts
  docs/system/components/PropRow.tsx
  docs/system/components/Props.tsx
  leda/components/StatusBar/StatusBar.test.tsx
  leda/components/StatusBar/StatusBar.tsx
  leda/components/StatusBar/helpers.tsx
  leda/components/StatusBar/types.ts
  package-lock.json
  package.json
  public/index.html
  styles/docs.scss
  webpack.config.js
  webpack.docs.js
Labels: bug

#50 Revert "FEND-909 MultiSelect: create checkboxes"
  demo/components/AutoComplete/CompareObjectsBy.tsx
  demo/components/MultiSelect/DataTypes.tsx
  demo/components/MultiSelect/GroupedData.tsx
  leda/commonTypes/index.ts
  leda/components/AutoComplete/handlers.ts
  leda/components/AutoComplete/helpers.ts
  leda/components/AutoComplete/index.tsx
  leda/components/AutoComplete/types.ts
  leda/components/DropDownSelect/index.tsx
  leda/components/LedaProvider/__snapshots__/LedaProvider.test.tsx.snap
  leda/components/MultiSelect/TagsContainer.tsx
  leda/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
  leda/components/MultiSelect/handlers.ts
  leda/components/MultiSelect/helpers.ts
  leda/components/MultiSelect/index.tsx
  leda/components/MultiSelect/types.ts
  leda/index.ts
  leda/src/SuggestionList/GroupLabel.tsx
  leda/src/SuggestionList/SelectAll.tsx
  leda/src/SuggestionList/SuggestionItem.tsx
  leda/src/SuggestionList/SuggestionList.tsx
  leda/src/SuggestionList/handlers.ts
  leda/src/SuggestionList/helpers.ts
  leda/src/SuggestionList/theme.ts
  leda/src/SuggestionList/types.ts
  leda/utils/checkIsTheSameObject.ts
  leda/utils/helpers.ts
  leda/utils/index.ts
  package-lock.json
  styles/themes/leda/components/SuggestionList/_suggestion-list.scss
Labels: misc

#47 update release workflow
  .github/workflows/release.yml
  package.json
Labels: misc

#18 FEND-957 DropDownSelect: fix onFilterChange bug
  demo/components/DropDownSelect/BoundingElementRef.tsx
  demo/components/DropDownSelect/CompareObjectsBy.tsx
  demo/components/DropDownSelect/DataTypes.tsx
  demo/components/DropDownSelect/EmptyValues.tsx
  demo/components/DropDownSelect/Filterable.tsx
  demo/components/DropDownSelect/GroupedObjectsData.tsx
  demo/components/DropDownSelect/ObjectsData.tsx
  leda/components/DropDownSelect/DropDownSelect.test.tsx
  leda/components/DropDownSelect/handlers.ts
  leda/components/DropDownSelect/hooks.ts
  leda/components/DropDownSelect/index.tsx
  leda/components/DropDownSelect/types.ts
Labels: feature, jira

#19 FEND-958 DateTimeInput: fix date helper
  leda/src/DateTimeInput/helpers.ts
Labels: feature, jira, wip

#40 Feature/fend 909 styles
  README.md
  package.json
  styles/themes/leda/components/SuggestionList/_suggestion-list.scss
  webpack.config.js
Labels: jira, styles

#66 fix form validation
  leda/form/form.ts
  leda/form/helpers.ts
Labels: bug

#56 MaskedInput: fix circular focus bug
  leda/src/MaskedInputBase/handlers.ts
Labels: bug

#64 Input: fix null as value
  demo/components/Input/Basic.tsx
  demo/components/Input/Customization.tsx
  leda/components/Input/helpers.ts
  leda/components/Input/index.tsx
  leda/components/Input/types.ts
Labels: bug

#57 update source mapping
  styles/reset.scss
  webpack.config.js
Labels: misc

#55 Notifications: add actionButtonRender and method in change event
  demo/Demo.tsx
  demo/components/Notifications.tsx
  leda/components/Notifications/NotificationItem.tsx
  leda/components/Notifications/Notifications.test.tsx
  leda/components/Notifications/Notifications.tsx
  leda/components/Notifications/__snapshots__/Notifications.test.tsx.snap
  leda/components/Notifications/constants.ts
  leda/components/Notifications/types.ts
  styles/helpers.scss
  styles/themes/light/components/Notifications/_notifications.scss
Labels: feature

#78 StatusBar: add currentStepProgress
  demo/components/StatusBar.tsx
  leda/components/StatusBar/StatusBar.tsx
  leda/components/StatusBar/StatusBarItem.tsx
  leda/components/StatusBar/__snapshots__/StatusBar.test.tsx.snap
  leda/components/StatusBar/types.ts
  styles/themes/light/components/StatusBar/_statusbar.scss
Labels: feature

#53 FEND-956 Tooltip: fix style bug
  demo/components/StateButtonGroup.tsx
  demo/components/Tooltip.tsx
  demo/index.tsx
  leda/components/Tooltip/Tooltip.test.tsx
  leda/components/Tooltip/TooltipBody.tsx
  leda/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
  leda/components/Tooltip/constants.ts
  leda/components/Tooltip/helpers.ts
  leda/components/Tooltip/hooks.ts
  leda/components/Tooltip/index.tsx
  leda/components/Tooltip/theme.ts
  leda/components/Tooltip/types.ts
Labels: feature, jira

#82 update some files and tests
  docs/stories/Layout/StatusBar/Props/StatusItemType.tsx
  leda/components/DropDownSelect/DropDownSelect.test.tsx
  leda/components/StatusBar/StatusBar.test.tsx
  leda/components/StatusBar/__snapshots__/StatusBar.test.tsx.snap
  leda/utils/getFileWordEnding.test.tsx
  leda/utils/useTheme.ts
  package.json
Labels: misc

#67 Button group
  cypress/integration/ButtonGroup/index.spec.js
  cypress/integration/DateRange/index.spec.js
  cypress/support/commands.js
  demo/CypressLayout.tsx
  demo/cypress/ButtonGroup/index.tsx
  demo/cypress/DateRange/index.tsx
  demo/cypress/index.ts
Labels: test

#88 AutoComplete: add wrapper to fix border bug
  cypress/integration/AutoComplete/index.spec.js
  demo/components/Validation/FormControlled.tsx
  demo/components/Validation/FormUncontrolled.tsx
  leda/components/AutoComplete/__snapshots__/AutoComplete.test.tsx.snap
  leda/components/AutoComplete/index.tsx
  leda/components/AutoComplete/theme.ts
  leda/components/DropDownSelect/index.tsx
  leda/components/Input/index.tsx
  leda/components/MultiSelect/index.tsx
  styles/themes/light/components/AutoComplete/_autocomplete.scss
Labels: bug

#89 NumericTextBox: fix letters bug
  leda/components/NumericTextBox/helpers.ts
Labels: bug

#51 FEND-917 Tabs: add isDisabled
  demo/components/Tabs.tsx
  leda/components/Tabs/Tab.tsx
  leda/components/Tabs/theme.ts
  leda/components/Tabs/types.ts
  styles/themes/light/components/Tabs/_tabs.scss
Labels: feature

#71 DropZone, FileDrop, FileUpload: add validation
  .gitignore
  cypress/screenshots/AutoComplete/index.spec.js/AutoComplete -- Display -- should render ClearButton (failed).png
  cypress/screenshots/AutoComplete/index.spec.js/AutoComplete -- Display -- should render loader when isLoading (failed).png
  cypress/videos/AutoComplete/index.spec.js.mp4
  demo/components/DropZone/ControlledDropZone.tsx
  demo/components/DropZone/UncontrolledDropZone.tsx
  demo/components/FileDrop/ControlledFileDrop.tsx
  demo/components/FileUpload/Controlled.tsx
  leda/components/DropZone/DropZone.tsx
  leda/components/DropZone/__snapshots__/DropZone.test.tsx.snap
  leda/components/DropZone/handlers.ts
  leda/components/DropZone/helpers.tsx
  leda/components/DropZone/theme.ts
  leda/components/DropZone/types.ts
  leda/components/FileDrop/FileDrop.tsx
  leda/components/FileDrop/handlers.ts
  leda/components/FileDrop/helpers.tsx
  leda/components/FileDrop/theme.ts
  leda/components/FileDrop/types.ts
  leda/components/FileUpload/__snapshots__/FileUpload.test.tsx.snap
  leda/components/FileUpload/handlers.ts
  leda/components/FileUpload/index.tsx
  leda/components/FileUpload/types.ts
  leda/components/Validation/helpers.ts
  styles/helpers.scss
  styles/themes/light/components/DropZone/_dropzone.scss
  styles/themes/light/components/FileDrop/_file-drop.scss
Labels: feature

#90 Input: fix hasClearButton bug in controlled mode
  demo/components/Input/Customization.tsx
  leda/components/Input/Input.test.tsx
  leda/components/Input/__snapshots__/Input.test.tsx.snap
  leda/components/Input/handlers.ts
  leda/components/Input/helpers.ts
  leda/components/Input/index.tsx
  leda/components/Input/types.ts
  styles/themes/light/components/Input/_input.scss
Labels: bug

#92 NumericTextBox: fix undefined bug
  leda/components/NumericTextBox/NumericTextBox.test.tsx
  leda/components/NumericTextBox/__snapshots__/NumericTextBox.test.tsx.snap
  leda/components/NumericTextBox/handlers.ts
  leda/components/NumericTextBox/helpers.ts
  leda/components/NumericTextBox/hooks.tsx
  leda/components/NumericTextBox/index.tsx
  leda/components/NumericTextBox/types.ts
Labels: bug

#5 DateRange: add tests
  demo/cypress/DateRange/index.tsx
  package.json
Labels: test

#103 DropDown: fix dynamic position bug
  leda/components/DropDown/DropDown.test.tsx
  leda/components/DropDown/__snapshots__/DropDown.test.tsx.snap
  styles/themes/light/components/DropDown/_dropdown.scss
Labels: bug

#98 MultiSelect, NumericTextBox: fix validation bug
  demo/components/Validation/index.tsx
  leda/components/Validation/helpers.ts
  leda/components/Validation/useValidation.tsx
  leda/form/form.ts
  leda/form/helpers.ts
Labels: bug

#100 FEND-968 Types: extends event types, export Table types
  leda/components/AutoComplete/types.ts
  leda/components/MultiSelect/handlers.ts
  leda/components/MultiSelect/types.ts
  leda/components/Table/Col.ts
  leda/components/Table/ColGroup.ts
  leda/components/Table/TBody.ts
  leda/components/Table/TFoot.ts
  leda/components/Table/THead.ts
  leda/components/Table/Table.ts
  leda/components/Table/Td.ts
  leda/components/Table/Th.ts
  leda/components/Table/Tr.ts
  leda/components/Table/types.ts
  leda/index.ts
Labels: feature, jira

#113 ISSUE-106 MaskedInput: do not clear the not completely filled input field on blur
  leda/src/MaskedInputBase/handlers.ts
  leda/src/MaskedInputBase/index.tsx
  leda/src/MaskedInputBase/types.ts
Labels: enhancement

#112 ProgressBar: add custom render for value render
  demo/components/ProgressBar.tsx
  leda/components/ProgressBar/__snapshots__/ProgressBar.test.tsx.snap
  leda/components/ProgressBar/index.tsx
  leda/components/ProgressBar/theme.ts
  leda/components/ProgressBar/types.ts
Labels: feature
